# Generated by Django 3.1.4 on 2021-01-07 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20210107_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user_id',
            field=models.CharField(editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='yourpocket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='yourpocket',
            name='user_id',
            field=models.CharField(editable=False, max_length=512),
        ),
    ]
